version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@5"
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: build-project
          command: npm run generate
      - persist_to_workspace:
          root: ./
          paths:
            - dist
  upload:
    parameters:
      sas_token:
        type: string
      url:
        type: string
    docker:
      - image: circleci/python
    steps:
      - checkout
      - attach_workspace:
          at: ./
      - run: cd $PWD/dist; bash ../scripts/azure.sh << parameters.sas_token >> <<parameters.url >>
workflows:
  version: 2
  publish-updated-content:
    jobs:
      - build:
          name: build
      - upload:
          name: upload-test
          requires:
            - build
          sas_token: ${SAS_TOKEN_TEST}
          url: https://swarmstoraccount.blob.core.windows.net/oslo-webuniversum3/dist.tar
      - hold:
          type: approval # presents manual approval button in the UI
          requires:
            - upload-test
